services:
  opensearch:
    image: opensearchproject/opensearch:3
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASSWORD}
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - 9200:9200
      - 9600:9600
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - OS_HOST=http://opensearch:9200   # container-to-container DNS
    depends_on:
      opensearch:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  opensearch-data:
