services:
  opensearch:
    image: opensearchproject/opensearch:3
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASSWORD}
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - 9200:9200
      - 9600:9600
    volumes:
      - opensearch-data:/usr/share/opensearch/data

volumes:
  opensearch-data:
