name: PR

on:
  push:
    branches:
      - feat/opensearch-init

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build & start stack
        run: |
          docker compose -f compose.yml up -d --build

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install deps
        run: uv sync

      - name: Create index
        env:
          OS_HOST: "http://localhost:9200"
        run: |
          # Ensure your package imports work when running a script directly
          export PYTHONPATH="$PWD"
          uv run python scripts/create_index.py
